apiVersion: apps/v1
kind: Deployment

metadata:
  name: cloud-platform-application

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      application: cloud-platform-application

  template:
    metadata:
      labels:
        application: cloud-platform-application

    spec:
      containers:
        - name: cloud-platform-application
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10