name: Application Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  validate-application:
    runs-on: ubuntu-latest

    steps:
      - name: Download repository code
        uses: actions/checkout@v6

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          enable-cache: true

      - name: Install locked dependencies
        run: uv sync --locked --dev

      - name: Run ruff link actions/checkout
        run: uv run ruff check .

      - name: Check ruff formatting
        run: uv run ruff format --check .

      - name: Run automated tests
        run: uv run python -m pytest -v

      - name: Build Docker image
        run: docker build --tag cloud-platform-application:ci .